package com.oosic.webservice.model.po;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.ID
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Alias
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Password
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Email
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.create_date
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.modified_date
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Background_Url
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private String backgroundUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Is_Deleted
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Birthday
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Gender
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Avatar
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.Source
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.ID
     *
     * @return the value of tb_account.ID
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.ID
     *
     * @param id the value for tb_account.ID
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Alias
     *
     * @return the value of tb_account.Alias
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Alias
     *
     * @param alias the value for tb_account.Alias
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Password
     *
     * @return the value of tb_account.Password
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Password
     *
     * @param password the value for tb_account.Password
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Email
     *
     * @return the value of tb_account.Email
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Email
     *
     * @param email the value for tb_account.Email
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.create_date
     *
     * @return the value of tb_account.create_date
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.create_date
     *
     * @param createDate the value for tb_account.create_date
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.modified_date
     *
     * @return the value of tb_account.modified_date
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.modified_date
     *
     * @param modifiedDate the value for tb_account.modified_date
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Background_Url
     *
     * @return the value of tb_account.Background_Url
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public String getBackgroundUrl() {
        return backgroundUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Background_Url
     *
     * @param backgroundUrl the value for tb_account.Background_Url
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setBackgroundUrl(String backgroundUrl) {
        this.backgroundUrl = backgroundUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Is_Deleted
     *
     * @return the value of tb_account.Is_Deleted
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Is_Deleted
     *
     * @param isDeleted the value for tb_account.Is_Deleted
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Birthday
     *
     * @return the value of tb_account.Birthday
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Birthday
     *
     * @param birthday the value for tb_account.Birthday
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Gender
     *
     * @return the value of tb_account.Gender
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Gender
     *
     * @param gender the value for tb_account.Gender
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Avatar
     *
     * @return the value of tb_account.Avatar
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Avatar
     *
     * @param avatar the value for tb_account.Avatar
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.Source
     *
     * @return the value of tb_account.Source
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.Source
     *
     * @param source the value for tb_account.Source
     *
     * @mbggenerated Fri Nov 22 11:32:43 CST 2013
     */
    public void setSource(String source) {
        this.source = source;
    }
}